services:
  mongo:
    image: mongo:latest
    hostname: "mongo{{.Task.Slot}}"
    networks:
      - mongo-cluster
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: any
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  mongo-cluster:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  mongo-data:
    name: mongo-data
